ALTER TABLE cross_seed_settings
    ADD COLUMN enable_pooled_partial_completion BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN allow_reflink_single_file_size_mismatch BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN max_missing_bytes_after_recheck BIGINT NOT NULL DEFAULT 104857600;

CREATE TABLE cross_seed_partial_pool_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_instance_id BIGINT NOT NULL,
    source_hash TEXT NOT NULL,
    target_instance_id BIGINT NOT NULL,
    target_hash TEXT NOT NULL,
    target_hash_v2 TEXT,
    target_added_on BIGINT NOT NULL DEFAULT 0,
    target_name TEXT NOT NULL DEFAULT '',
    mode TEXT NOT NULL,
    managed_root TEXT NOT NULL,
    source_piece_length BIGINT NOT NULL DEFAULT 0,
    max_missing_bytes_after_recheck BIGINT NOT NULL DEFAULT 104857600,
    source_files_json TEXT NOT NULL DEFAULT '[]',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    UNIQUE(target_instance_id, target_hash)
);

CREATE INDEX idx_cross_seed_partial_pool_members_source
    ON cross_seed_partial_pool_members(source_instance_id, source_hash);

CREATE INDEX idx_cross_seed_partial_pool_members_expires
    ON cross_seed_partial_pool_members(expires_at);
